---
# tasks file for coredns
- block:
    - name: copy coredns yaml file
      template:
        src: coredns-{{ coredns_version }}.yml.j2
        dest: /yaml/coredns-{{ coredns_version }}.yml
    - name: install coredns
      shell: kubectl apply -f /yaml/coredns-{{ coredns_version }}.yml \
                     --kubeconfig=/etc/kubernetes/kubeconfig
  run_once: true
