---
# tasks file for lb
- name: install HAProxy and keepalived
  apt: 
    name:
      - haproxy
      - keepalived
    state: present
    update_cache: yes
- name: Copy keepalived config file
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
- name: Copy haproxy config
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
- name: Copy check script
  copy:
    src: check-haproxy.sh
    dest: /usr/bin/check-haproxy.sh
    mode: 755
- name: Restart the services
  systemd:
    name: "{{ item }}"
    state: restarted
    enabled: true
    daemon_reload: true
  with_items:
    - haproxy.service
    - keepalived.service

- name: Change .kube/config file
  blcok:
    - name: Change admin-config file
      lineinfile:
        dest: certs/kubectl.kubeconfig
        regexp: "^    server"
        line: "    server: https://{{ VIP_ADDRESS }}:{{ SECURE_PORT }}"
    - name: Copy new config to master
      shell: "scp certs/kubectl.kubeconfig 192.168.3.101:~/.kube/config && \
              scp certs/kubectl.kubeconfig 192.168.3.102:~/.kube/config && \
              scp certs/kubectl.kubeconfig 192.168.3.103:~/.kube/config"
