---
# tasks file for lb
- name: install HAProxy and keepalived
  apt: 
    name:
      - haproxy
      - keepalived
    state: present
    update_cache: yes
- name: Copy keepalived config file
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
- name: Copy haproxy config
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
- name: Copy check script
  copy:
    src: check-haproxy.sh
    dest: /usr/bin/check-haproxy.sh
    mode: 755
- name: Set the service to start upon startup
  shell: systemctl daemon-reload && systemctl enable haproxy.service && systemctl enable keepalived.service
- name: Rstart service
  shell: systemctl restart haproxy.service && systemctl restart keepalived.service
