---
# var
SECURE_PORT: 6443
SERVICE_CIDR: 172.16.0.0/16
NODE_PORT_RANGE: 30000-32767
CLUSTER_CIDR: 10.0.0.0/16
NODE_CIDR_LEN: 24
CLUSTER_NAME: k8s
KUBE_APISERVER: "{{ groups['master'][0] }}"
PROXY_MODE: ipvs
CLUSTER_NETWORK: calico
CLUSTER_DNS: coredns
CLUSTER_DNS_DOMAIN: devcoffee.local
VIP_ADDRESS: 192.168.3.205
