---
- name: install etcd
  hosts: master
  tasks:
    - name: Create a directoy for etcd
      file:
        path: /etc/kubernetes/etcd/data
        state: directory
    - name: Create a directory for ssl
      file:
        path: /etc/kubernetes/ssl
        state: directory
    - name: copy binary file
      copy:
        src: bin/{{ item }}
        dest: /usr/local/bin/
        mode: 755
      with_items:
        - etcd
        - etcdctl
    - name: copy service file
      copy:
        src: service/etcd.service
        dest: /usr/lib/systemd/system/etcd.service
    - name: Copy ectd configure file
      template:
        src: config/etcd.conf.j2
        dest: /etc/kubernetes/etcd/etcd.conf
    - name: Copy cert file
      copy:
        src: certs/{{ item }}
        dest: /etc/kubernetes/ssl/
      with_items:
        - etcd_server.csr
        - etcd_server.crt
        - etcd_server.key
        - etcd_client.key
        - etcd_client.csr
        - etcd_client.crt
        - ca.crt
    - name: Set the service to start upon startup
      shell: systemctl daemon-reload && systemctl enable etcd.service
    - name: Rstart etcd service
      shell: systemctl restart etcd.service
