---
- name: install HA
  hosts: ha
  tasks:
    - name: install HAProxy and keepalived
      apt: 
        name:
          - haproxy
          - keepalived
        state: present
        update_cache: yes
    - name: Copy keepalived config file
      template:
        src: config/keepalived_master.conf.j2
        dest: /etc/keepalived/keepalived.conf
      when: ansible_facts['fqdn'] == "ha1"
    - name: Copy keepalived config file
      template:
        src: config/keepalived_back.conf.j2
        dest: /etc/keepalived/keepalived.conf
      when: ansible_facts['fqdn'] == "ha2"
    - name: Copy haproxy config
      template:
        src: config/haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
    - name: Copy check script
      copy:
        src: script/check-haproxy.sh
        dest: /usr/bin/check-haproxy.sh
        mode: 755
    - name: Set the service to start upon startup
      shell: systemctl daemon-reload && systemctl enable haproxy.service && systemctl enable keepalived.service
    - name: Rstart etcd service
      shell: systemctl restart haproxy.service && systemctl restart keepalived.service
