---
- name: Install harbor
  hosts: harbor
  tasks:
    - name: Add apt key and repo
      block:
        - name: somerepo that no apt key
          get_url:
            url: http://mirror.nju.edu.cn/docker-ce/linux/ubuntu//gpg
            dest: /etc/apt/trusted.gpg.d/dockerrepo.asc
        - name: somerepo | apt source
          apt_repository:
            repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/dockerrepo.asc] http://mirror.nju.edu.cn/docker-ce/linux/ubuntu {{ ansible_distribution_release }} stable"
            state: present
    - name: Install docker-ce and docker-compose
      apt:
        pkg:
          - docker-ce 
          - docker-ce-cli
          - docker-compose
        state: present
        update_cache: yes
    - name: Copy harbor folder
      copy:
        src: harbor/harbor
        dest: /
        mode: 775
    - name: Copy harbor.yml file
      template:
        src: config/harbor.yml.j2
        dest: /harbor/harbor.yml
    - name: Create cert
      block:
        - name: Check cert stat
          stat:
            path: certs/harbor.cert
          register: v3
        - name: Crete v3 file
          template:
            src: config/v3.ext.j2
            dest: certs/v3.ext
          when: "v3.stat.isreg is not defined"
        - name: Create a key
          shell: openssl genrsa -out certs/harbor.key 4096
          when: "v3.stat.isreg is not defined"
        - name: Create a csr file
          shell: openssl req -sha512 -new -subj "/CN=devcoffee.local" \
                         -key certs/harbor.key -out certs/harbor.csr
          when: "v3.stat.isreg is not defined"
        - name: Create cert file
          shell: openssl x509 -req -sha512 -days 3650 \
                         -extfile certs/v3.ext -CA certs/ca.crt \
                         -CAkey certs/ca.key -CAcreateserial \
                         -in certs/harbor.csr -out certs/harbor.crt
          when: "v3.stat.isreg is not defined"
        - name: change cert to support docker
          shell: openssl x509 -inform PEM -in certs/harbor.crt -out certs/harbor.cert
          when: "v3.stat.isreg is not defined"
      delegate_to: localhost
    - name: create a directory for cert
      file:
        path: /data/cert
        state: directory
    - name: Copy cert file to cert dir
      copy:
        src: certs/{{ item }}
        dest: /data/cert
      with_items:
        - harbor.crt
        - harbor.key
    - name: create a direcoty for docker
      file:
        path: /etc/docker/certs.d/harbor
        state: directory
    - name: Copy cert file to docker
      copy:
        src: certs/{{ item }}
        dest: /etc/docker/certs.d/harbor
      with_items:
        - harbor.cert
        - harbor.key
        - ca.crt
    - name: restart docker service
      shell: systemctl restart docker.service
    - name: install harbor
      shell: "cd /harbor && \
              ./install.sh >> /tmp/harbor-`date +'%Y%m%d%H%M%S'`.log 2>&1"
