---
- name: Install kube-controller-manager
  hosts: master
  tasks:
    - name: Copy service file
      copy:
        src: service/kube-controller-manager.service
        dest: /usr/lib/systemd/system/kube-controller-manager.service
    - name: Copy kube-controller-manager config
      copy:
        src: config/kube-controller-manager.j2
        dest: /etc/kubernetes/kube-controller-manager
    - name: Set the service to start upon startup
      shell: systemctl daemon-reload && systemctl enable kube-controller-manager.service
    - name: Rstart kube-controller-manager service
      shell: systemctl restart kube-controller-manager.service

