---
- name: Install kube-scheduler
  hosts: master
  tasks:
    - name: Copy service file
      copy:
        src: service/kube-scheduler.service
        dest: /usr/lib/systemd/system/kube-scheduler.service
    - name: Copy kube-scheduler config
      copy:
        src: config/kube-scheduler.j2
        dest: /etc/kubernetes/kube-scheduler
    - name: Set the service to start upon startup
      shell: systemctl daemon-reload && systemctl enable kube-scheduler.service
    - name: Rstart kube-scheduler service
      shell: systemctl restart kube-scheduler.service

