---
- name: Deploy kubernetes
  hosts: all
  vars_files:
    - config.yml
  roles:
    - name: Initialize the OS
      role: prepare
    - name: Create certs
      role: certs
      delegate_to: localhost
      run_once: true
    - name: Deploy etcd
      role: etcd
      when: "inventory_hostname in groups['etcd']"
    - name: Deploy master node
      role: master
      when: "inventory_hostname in groups['master']" 
    - name: Deploy work node
      role: work
      when: "inventory_hostname in groups['work']"
