---
- name: Deploy kubernetes
  hosts: all
  vars_files:
    - config/config.yml
  roles:
    - name: Create certs
      role: certs
      delegate_to: localhost
      run_once: true
      when: INSTALL_MODE == 'binary'

    - name: Initialize the OS
      role: prepare
      tags: prepare os

    - name: Deploy LB
      role: lb
      when:
        - "groups['ha']|length > 0"
        - "inventory_hostname in groups['ha']"
      tags: deploy lb
  tasks:
    - include_tasks: kubeadm.yml
      when: INSTALL_MODE == 'kubeadm'

    - include_tasks: binary.yml
      when: INSTALL_MODE == 'binary'

    - include_tasks: plugins.yml
      


