---
- name: Install network plug-in
  hosts: 192.168.3.101
  tasks:
    - name: Create a directory for yaml file
      file:
        path: /yaml
        state: directory
        mode: 777
    - name: Copy calico yaml file
      template:
        src: config/calico-v3.25.yaml.j2
        dest: /yaml/calico-v3.25.yaml
    - name: Install network plug-in
      shell: kubectl apply -f /yaml/calico-v3.25.yaml \
                     --kubeconfig=/etc/kubernetes/kubeconfig
