---
# tasks file for prepare
- name: Copy file to server
  template:
    src: hosts.j2
    dest: /etc/hosts
    backup: yes

- name: check apt lock
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /var/lib/dpkg/lock
    - /var/lib/dpkg/lock-frontend

- name: Install software packages
  apt:
    name:
      - chrony
      - ipvsadm
      - ipset
      - bash-completion
      - nfs-common
      - libseccomp2
    state: latest
    update_cache: true
- name: Disabled swap 1
  lineinfile:
    path: /etc/fstab
    regexp: 'swap'
    state: absent
    backup: 'yes'
- name: Disabled swap 2
  shell: "swapoff -a"

- name: Copy modules file
  template:
    src: modules.conf.j2
    dest: /etc/modules-load.d/k8s-modules.conf
- name: Upload modules
  modprobe:
    name: "{{ item }}" 
    state: present
  loop:
    - overlay
    - br_netfilter
    - ip_vs
    - ip_vs_rr
    - ip_vs_wrr
    - ip_vs_sh
    - nf_conntrack

- name: Copy sysctl file
  template:
    src: k8s.conf.j2
    dest: /etc/sysctl.d/k8s.conf
- name: Apply sysctl file
  shell: "sysctl -p /etc/sysctl.d/k8s.conf"

- name: time zone
  shell: timedatectl set-timezone {{ TIMEZONE }} 
- name: Disabled RTC sync
  shell: timedatectl set-local-rtc false

- name: time sync
  template:
    src: chrony.conf.j2
    dest: /etc/chrony/chrony.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify: restart service

- name: Crate kubernetes directior
  file:
    path: /etc/kubernetes/
    state: directory
