---
# vars file for certs
CERT_EXPIRY: 87600h
CUSTOM_EXPIRY: 8760h
CA_EXPIRY: 87600h
CLUSTER_KUBERNETES_SVC_IP: "{{ SERVICE_CIDR.split('.')[0] }}.{{ SERVICE_CIDR.split('.')[1] }}.{{ SERVICE_CIDR.split('.')[2] }}.{{ SERVICE_CIDR.split('.')[3]|int + 1 }}"
CLUSTER_HOSTS:
  - 192.168.3.220
