---
# tasks file for etcd
- name: unarchive docker package
  unarchive:
    src: bin/etcd-v{{ ETCD_VERSION }}-linux-amd64.tar.gz
    dest: /tmp
- name: Create a directoy for etcd
  file:
    path: /etc/kubernetes/etcd/data
    state: directory

- name: get certs directory info
  stat:
    path: certs/
  register: ssl

- name: Creste a dir for certs
  file:
    path: /etc/kubernetes/ssl
    state: directory
  when: "ssl.stat.isreg is not defined"

- name: Copy the bin file
  copy:
    src: /tmp/etcd-v{{ ETCD_VERSION }}-linux-amd64/{{ item }}
    dest: /usr/local/bin
    remote_src: yes
    mode: 755
  with_items:
    - etcd
    - etcdctl
- name: copy service file
  template:
    src: etcd.service.j2 
    dest: /etc/systemd/system/etcd.service
- name: Copy cert file
  copy:
    src: certs/{{ item }}
    dest: /etc/kubernetes/ssl/
  with_items:
    - ca.pem
    - etcd.pem
    - etcd-key.pem
- name:  Start the service
  systemd:
    name: etcd.service
    state: started
    enabled: true
    daemon_reload: true
- name: check the etcd service
  shell: "systemctl is-active etcd.service"
  register: etcd_status
  until: '"active" in etcd_status.stdout'
  retries: 8
  delay: 8
