---
# 此文件用于定义 Ansible 在执行过程中使用的变量，这些变量根据环境的不同，具体的值可能有很大的差异。

# INSTALL_MODE 表示安装 kubernetes 的方式，其值可以是 binary，kubeadm
# binary 表示使用二进制的方式安装
# kubeadm 表示使用 kubeadm 的方式安装
INSTALL_MODE: "binary"

# RUNTIME 定义 kubernetes 群集使用的 Runtime，其值可以是 containerd，docker
RUNTIME: "containerd"

############################
# role:deploy
############################
# default: ca will expire in 100 years
# default: certs issued by the ca will expire in 50 years
CA_EXPIRY: "876000h"
CERT_EXPIRY: "438000h"

# force to recreate CA and other certs, not suggested to set 'true'
CHANGE_CA: false

# kubeconfig 配置参数
CLUSTER_NAME: "prod"
CONTEXT_NAME: "context-{{ CLUSTER_NAME }}"


# API server 的地址以及使用的端口
API_SERVER_IP: "{{ groups['master'][0] }}"
KUBE_APISERVER: "{{ hostvars[API_SERVER_IP]['ansible_default_ipv4']['address'] }}"
SECURE_PORT: 6443

# VIP 地址（只有配置 HAProxy 时才会生效）
VIP_ADDRESS: 192.168.3.100

# 如果有自己的loadbalancer，或者自定义的域名，可以添加到这里
CLUSTER_HOSTS:
  - 192.168.3.220

PAUSE_IMAGE: "registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.8"


# kubernetes service 的网络范围，以及NodePort 模式下可以使用的端口范围
SERVICE_CIDR: 192.168.0.0/16
NODE_PORT_RANGE: 30000-32767

# Pod 可以使用的网络范围，以及单个节点上面 Pod 可以使用的网络大小
CLUSTER_CIDR: 172.16.0.0/16
NODE_CIDR_LEN: 24


# kube-proxy 使用的模式，ipvs 或 iptables
PROXY_MODE: ipvs


# 定义 etcd 的版本
ETCD_VERSION: v3.5.9

# Kubernetes 可选插件
CLUSTER_NETWORK: calico
CLUSTER_DNS: coredns
CLUSTER_DNS_DOMAIN: devcoffee.local

# Kubernetes 可选插件
Kubernete_Dashboar_Install: "True"


# Harbor 配置
# 无论是否安装 harbor，不要注释掉INSTALL_HARBOR，因为配置 containerd 的时候需要使用到该变量，如果不需要安装 harbor，则将此值改为 FALSE 即可。
# 你也可以通过设置此值为 true，并将 HARBOR_DOMAIN 改成自己的harbor 地址。
INSTALL_HARBOR: false
#HARBOR_DOMAIN: harbor.devcoffee.local
