---
- name: Create etcd cert request
  template:
    src: etcd-csr.json.j2
    dest: certs/etcd-csr.json

- name: Create etcd cert key
  shell: "cd certs/ && \
          cfssl gencert -ca=ca.pem \
          -ca-key=ca-key.pem \
          -config=ca-config.json \
          -profile=kubernetes etcd-csr.json | cfssljson -bare etcd"
