---
- name: Copy kube-proxy cert request file
  template:
    src: kube-proxy-csr.json.j2
    dest: certs/kube-proxy-csr.json

- name: Create the certs for kube-proxy
  shell: "cd certs/ && \
          ../bin/cfssl gencert -ca=ca.pem -ca-key=ca-key.pem \
          -config=ca-config.json \
          -profile=kubernetes kube-proxy-csr.json | ../bin/cfssljson \
          -bare kube-proxy"

- name: Setting cluster
  shell: "cd certs/ && \
          ../bin/kubernetes/server/bin/kubectl config set-cluster kubernetes \
          --certificate-authority=ca.pem --embed-certs=true \
          --server=https://{{ KUBE_APISERVER }}:{{ SECURE_PORT }} \
          --kubeconfig=kube-proxy.kubeconfig"

- name: Setting client
  shell: "cd certs/ && \
          ../bin/kubernetes/server/bin/kubectl config set-credentials kube-proxy \
          --client-certificate=kube-proxy.pem \
          --embed-certs=true \
          --client-key=kube-proxy-key.pem \
          --kubeconfig=kube-proxy.kubeconfig"

- name: Setting context
  shell: "cd certs/ && \
          ../bin/kubernetes/server/bin/kubectl config set-context default \
          --cluster=kubernetes \
          --user=kube-proxy \
          --kubeconfig=kube-proxy.kubeconfig"

- name: Default contex
  shell: "cd certs/ && \
          ../bin/kubernetes/server/bin/kubectl config use-context default \
          --kubeconfig=kube-proxy.kubeconfig"
