---
- name: cert request file
  template:
    src: admin-csr.json.j2
    dest: certs/admin-csr.json

- name: Create admin key
  shell: "cd certs/ && cfssl gencert \
        -ca=ca.pem -ca-key=ca-key.pem \
        -config=ca-config.json \
        -profile=kubernetes admin-csr.json | cfssljson -bare admin"

- name: Setting the cluster
  shell: "cd certs/ && \
          ../bin/kubernetes/server/bin/kubectl config set-cluster {{ CLUSTER_NAME }} \
          --certificate-authority=ca.pem --embed-certs=true \
          --server=https://{{ KUBE_APISERVER }}:{{ SECURE_PORT }} \
          --kubeconfig=kubectl.kubeconfig"
  
- name: Setting client
  shell: "cd certs/ && \
          ../bin/kubernetes/server/bin/kubectl config set-credentials admin \
          --client-certificate=admin.pem --embed-certs=true \
          --client-key=admin-key.pem \
          --kubeconfig=kubectl.kubeconfig"
  
- name: Setting context
  shell: "cd certs/ && \
          ../bin/kubernetes/server/bin/kubectl config set-context {{ CLUSTER_NAME }} \
          --cluster={{ CLUSTER_NAME }} --user=admin \
          --kubeconfig=kubectl.kubeconfig"
  
- name: default context
  shell: "cd certs/ && \
         ../bin/kubernetes/server/bin/kubectl config use-context {{ CLUSTER_NAME }} \
         --kubeconfig=kubectl.kubeconfig"
