---
- name: Copy kube-scheduler cert request file
  template:
    src: kube-scheduler-csr.json.j2
    dest: certs/kube-scheduler-csr.json

- name: Create kube-scheduler cert key
  shell:  "cd certs/ && \
           ../bin/cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json \
           -profile=kubernetes kube-scheduler-csr.json | ../bin/cfssljson \
           -bare kube-scheduler"

- name: Seting the cluster
  shell: "cd certs/ && \
          ../bin/kubernetes/server/bin/kubectl config set-cluster {{ CLUSTER_NAME }} \
          --certificate-authority=ca.pem --embed-certs=true \
          --server=https://{{ KUBE_APISERVER }}:{{ SECURE_PORT }} \
          --kubeconfig=kube-scheduler.kubeconfig"

- name: Seting Client
  shell: "cd certs/ && \
          ../bin/kubernetes/server/bin/kubectl config \
          set-credentials system:kube-scheduler \
          --client-certificate=kube-scheduler.pem \
          --client-key=kube-scheduler-key.pem \
          --embed-certs=true \
          --kubeconfig=kube-scheduler.kubeconfig"

- name: Setting context
  shell: "cd certs/ && \
          ../bin/kubernetes/server/bin/kubectl config \
          set-context default --cluster={{ CLUSTER_NAME }} \
          --user=system:kube-scheduler \
          --kubeconfig=kube-scheduler.kubeconfig"

- name: Default context
  shell: "cd certs/ && \
          ../bin/kubernetes/server/bin/kubectl config use-context default \
          --kubeconfig=kube-scheduler.kubeconfig"
