---
- name: Copy kube-controller-manager cert request file
  template:
    src: kube-controller-manager-csr.json.j2
    dest: certs/kube-controller-manager-csr.json

- name: Create kube-controller-manager key
  shell: "cd certs && \
          ../bin/cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json \
          -profile=kubernetes kube-controller-manager-csr.json | ../bin/cfssljson \
          -bare kube-controller-manager"

- name: Set the cluster
  shell: "cd certs && \
          ../bin/kubernetes/server/bin/kubectl config set-cluster {{ CLUSTER_NAME }} \
          --certificate-authority=ca.pem --embed-certs=true \
          --server=https://{{ KUBE_APISERVER }}:{{ SECURE_PORT }}  \
          --kubeconfig=kube-controller-manager.kubeconfig"

- name: Setting the client
  shell: "cd certs && \
         ../bin/kubernetes/server/bin/kubectl config \
         set-credentials system:kube-controller-manager \
         --client-certificate=kube-controller-manager.pem \
         --client-key=kube-controller-manager-key.pem --embed-certs=true \
         --kubeconfig=kube-controller-manager.kubeconfig"

- name: Setting context
  shell: "cd certs && \
          ../bin/kubernetes/server/bin/kubectl config set-context default \
          --cluster={{ CLUSTER_NAME }} --user=system:kube-controller-manager \
          --kubeconfig=kube-controller-manager.kubeconfig"

- name: Default context
  shell: "cd certs && \
          ../bin/kubernetes/server/bin/kubectl config use-context default \
          --kubeconfig=kube-controller-manager.kubeconfig"
