---
# tasks file for node
- name: Copy containerd binary file
  copy:
    src: bin/usr/local/bin/{{ item }}
    dest: /usr/local/bin/
    mode: preserve
  with_items:
    - containerd
    - containerd-shim-runc-v1
    - containerd-stress
    - critest
    - ctr
    - containerd-shim  
    - containerd-shim-runc-v2
    - crictl
    - ctd-decoder

- name: Copy containerd runc file
  copy:
    src: bin/usr/local/sbin/runc
    dest: /usr/local/sbin/
    mode: preserve

- name: Copy opt file
  copy:
    src: bin/opt/{{ item }}
    dest: /opt/
    mode: preserve
  with_items:
    - cni
    - containerd

- name: Copy service file
  copy:
    src: bin/etc/systemd/system/containerd.service
    dest: /etc/systemd/system/containerd.service
    mode: preserve

- name: Copy crictl yaml file
  copy:
    src: bin/etc/crictl.yaml
    dest: /etc/
    mode: preserve

- name: Copy cni config file
  copy:
    src: bin/etc/cni
    dest: /etc/
    mode: preserve

- name: Check the stat of /etc/containerd directory
  stat:
    path: /etc/containerd
  register: CD

- name: Create a direcotory for containerd
  file:
    path: /etc/containerd
    state: directory
  when: "CD.stat.isreg is not defined"

- name: Copy containerd config
  template:
    src: config.toml.j2
    dest: /etc/containerd/config.toml

- name: Start the service
  systemd:
    name: containerd.service
    state: started
    enabled: true
    daemon_reload: true

- name: Check the stat of /etc/kubernetes/ssl directory
  stat:
    path: /etc/kubernetes/ssl
  register: kube

- name: Create a direcotory for containerd
  file:
    path: /etc/kubernetes/ssl
    state: directory
  when: "kube.stat.isreg is not defined"

- name: Copy kubelet and kube-proxy binary file
  copy:
    src: bin/kubernetes/server/bin/{{ item }}
    dest: /usr/local/bin/
    mode: preserve
  with_items:
    - kubelet
    - kube-proxy

- import_tasks: kubelet-kubeconfig.yml

- name: Create some directories
  file:
    path: /var/lib/{{ item }}
    state: directory
  with_items:
    - kubelet
    - kube-proxy

- name: Create kubelet config
  template:
    src: kubelet-config.yaml.j2
    dest: /var/lib/kubelet/config.yaml

- name: Create kubelet service
  template:
    src: kubelet.service.j2
    dest: /etc/systemd/system/kubelet.service

- name: Copy kube-proxy.conf
  copy:
    src: certs/kube-proxy.kubeconfig
    dest: /etc/kubernetes/kube-proxy.kubeconfig

- name: Create kube-proxy config file
  template:
    src: kube-proxy-config.yaml.j2
    dest: /var/lib/kube-proxy/kube-proxy-config.yaml

- name: Copy kube-proxy service file
  template:
    src: kube-proxy.service.j2
    dest: /etc/systemd/system/kube-proxy.service

- name: Start the service
  systemd:
    name: "{{ item }}"
    state: started
    enabled: true
    daemon_reload: true
  with_items:
    - kubelet.service
    - kube-proxy.service
