---
# tasks file for coredns
- block:
  - name: get certs directory info
    stat: 
      path: /yaml
    register: d
  - name: Create a directory for yaml file
    file:
      path: /yaml
      state: directory
      mode: 777
    when: "d.stat.isreg is not defined"
  - name: copy coredns yaml file
    template:
      src: coredns-{{ COREDNS_VERSION }}.yml.j2
      dest: /yaml/coredns-{{ COREDNS_VERSION }}.yml
  - name: install coredns
    shell: kubectl apply -f /yaml/coredns-{{ COREDNS_VERSION }}.yml
  run_once: true
