---
# tasks file for calico
- block:
  - name: Create a directory for yaml file
    file:
      path: /yaml
      state: directory
      mode: 777
  - name: Copy calico yaml file
    template:
      src: calico-{{ calico_version }}.yaml.j2
      dest: /yaml/calico-{{ calico_version }}.yaml
  - name: Install network plug-in
    shell: kubectl apply -f /yaml/calico-{{ calico_version }}.yaml
  run_once: true
