---
# tasks file for master
- name: Copy binary file
  copy:
    src: bin/kubernetes/server/bin/{{ item }}
    dest: /usr/local/bin/
    mode: 0755
  with_items:
    - kube-apiserver
    - kube-scheduler
    - kube-controller-manager
    - kubectl
- name: Copy kube-api config
  template:
    src: kube-apiserver.j2
    dest: /etc/kubernetes/kube-apiserver
- name: Copy kubeconfig
  template:
    src: kubeconfig.j2
    dest: /etc/kubernetes/kubeconfig
- name: copy API Server certificate
  copy:
    src: certs/{{ item }}
    dest: /etc/kubernetes/ssl/
  with_items:
    - apiserver.crt
    - apiserver.csr
    - apiserver.key
    - client.crt
    - client.csr
    - client.key
- name: Copy kube-controller-manager config
  template:
    src: kube-controller-manager.j2
    dest: /etc/kubernetes/kube-controller-manager
- name: Copy kube-scheduler config
  template:
    src: kube-scheduler.j2
    dest: /etc/kubernetes/kube-scheduler
- name: Copy service file
  copy:
    src: "{{ item }}"
    dest: /usr/lib/systemd/system/
  with_items:
    - kube-apiserver.service
    - kube-controller-manager.service
    - kube-scheduler.service
- name: Reload the system service
  shell: systemctl daemon-reload 
- name: Set the service to start upon startup
  shell: systemctl enable kube-apiserver.service && \
         systemctl enable kube-controller-manager.service && \
         systemctl enable kube-scheduler.service
- name: Rstart service
  shell: systemctl restart kube-apiserver.service && \
         systemctl restart kube-controller-manager.service && \
         systemctl restart kube-scheduler.service 
- name: config --kubeconfig
  copy:
    src: k8s.sh
    dest: /etc/profile.d/
- name: apply
  shell: . /etc/profile.d/k8s.sh
