---
# tasks file for master
- name: Create some directory
  file: 
    name: ~/.kube
    state: directory
    mode: 0775

- name: get certs directory info
  stat:
    path: certs/
  register: ssl

- name: Creste a dir for certs
  file:
    path: /etc/kubernetes/ssl
    state: directory
  when: "ssl.stat.isreg is not defined"

- name: Copy binary file
  copy:
    src: bin/kubernetes/server/bin/{{ item }}
    dest: /usr/local/bin/
    mode: 0755
  with_items:
    - kube-apiserver
    - kube-scheduler
    - kube-controller-manager
    - kubectl

- name: Copy kubeconfig file
  copy: 
    src: certs/{{ item }} 
    dest: /etc/kubernetes/{{ item }}
  with_items:
    - kube-controller-manager.kubeconfig
    - kube-scheduler.kubeconfig

- name: Copy kubernetes certs
  copy:
    src: certs/{{ item }}
    dest: /etc/kubernetes/ssl/{{ item }}
  with_items:
    - ca.pem
    - ca-key.pem
    - apiserver.pem
    - apiserver-key.pem
    - aggregator-proxy.pem
    - aggregator-proxy-key.pem

- name: Copy service file
  template:
    src: "{{ item }}.j2" 
    dest: /etc/systemd/system/{{ item }}
  with_items:
    - kube-apiserver.service
    - kube-controller-manager.service
    - kube-scheduler.service

- name:  Start the service
  systemd:
    name: "{{ item }}"
    state: started
    enabled: true
    daemon_reload: true
  with_items:
    - kube-apiserver.service
    - kube-controller-manager.service
    - kube-scheduler.service

- name: Copy kubeconfig file
  copy:
    src: certs/kubectl.kubeconfig
    dest: ~/.kube/config
    mode: 0400

- name: Change admin-config file
  lineinfile:
    dest: ~/.kube/config
    regexp: "^    server"
    line: "    server: https://{{ VIP_ADDRESS }}:{{ SECURE_PORT }}"

- name: Get user:kubernetes role binding info
  shell: "kubectl get clusterrolebindings | grep kubelet-api-admin || echo 'notfound'"
  register: crb_info
  run_once: true

- name: Create user:kubernetes role binding
  shell: "kubectl create clusterrolebinding system:kubelet-api-admin \
          --clusterrole=system:kubelet-api-admin --user=kubernetes"
  run_once: true
  when: "'notfound' in crb_info.stdout"
