---
# tasks file for roles/containerd
- name: unarchive containerd package
  unarchive:
    src: bin/containerd-{{ CONTAINERD_VERSION }}-linux-amd64.tar.gz
    dest: /tmp/
- name: Copy containerd files to remote hosts
  copy:
    src: /tmp/bin/
    dest: /usr/local/bin/
    remote_src: yes

# Install runc
- name: Copy runc to remote host
  copy:
    src: bin/runc.amd64
    dest: /tmp
- name: Install runc
  shell: install -m 755 /tmp/runc.amd64 /usr/local/sbin/runc

# Install CNI plugins
- name: Create bin directory for cni plugins
  file:
    path: /opt/cni/bin/
    state: directory
- name: unarchive cni package
  unarchive:
    src: bin/cni-plugins-linux-amd64-v{{ CNI_VERSION }}.tgz
    dest: /opt/cni/bin/

- name: unarchive crictl
  unarchive:
    src: bin/crictl-v{{ CRICTL_VERSION }}-linux-amd64.tar.gz
    dest: /usr/local/bin/
- name: Create crictl yaml file
  template:
    src: crictl.yaml.j2
    dest: /etc/crictl.yaml

- name: create a directory for config file
  file:
    path: /etc/containerd
    state: directory

- name: copy config files
  template:
    src: config.toml.j2
    dest: /etc/containerd/config.toml

- name: Copy service file for containerd
  template:
    src: containerd.service.j2
    dest: /etc/systemd/system/containerd.service

- name: start the service
  systemd:
    name: containerd.service
    state: started
    enabled: true
    daemon_reload: true

- name: check the containerd service
  shell: "systemctl is-active containerd.service"
  register: containerd_status
  until: '"active" in containerd_status.stdout'
  retries: 8
  delay: 2 
